FROM fedora:38

RUN dnf update -y && \
    dnf install -y gcc make openssl openssl-devel && \
    dnf install -y nano && \
    dnf clean all && \
    rm -rf /var/cache/dnf

WORKDIR /app

COPY . .

RUN gcc src/server.c -o server -lssl -lcrypto && \
    gcc src/client.c -o client -lssl -lcrypto


CMD ["/bin/bash"]