FROM fedora:38

RUN dnf update -y && \
    dnf install -y gcc make openssl openssl-devel ninja-build meson && \
    dnf clean all && \
    rm -rf /var/cache/dnf

WORKDIR /app

COPY . .

RUN meson setup builddir && \
    meson compile -C builddir

CMD ["/bin/bash"]
